name: Deployment
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & Publish Image
        uses: elgohr/Publish-Docker-Github-Action@2.7
        with:
          name: docker.pkg.github.com/${{ github.repository }}/discord-bot
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_names: true
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      -
        name: Install Key
        uses: shimataro/ssh-key-action@v1.3.0
        with:
          private-key: ${{ secrets.SSH_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        env:
          DOCKER_HOST: ssh://${{ secrets.FTP_USER }}@${{ secrets.FTP_HOST }}"
          DOCKER_NAME: photon-bot
          DOCKER_IMG_VERSION: latest
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
        run: |
          scp $FTP_USER@$FTP_HOST:~/env-"$DOCKER_NAME" .env
          docker-compose up -d bot
